Model:
    CharSet: [' ', Q, E, '4', M, '6', U, D, G, F, B, '3', A, X, R, K, P, '8', J, T,
        '9', L, N, V, '2', W, Y, '5', Z, '7', S, C, H, I]
    ImageChannel: 1
    ImageHeight: 64
    ImageWidth: -1
    Word: false
System:
    Allow_Ext: [jpg, jpeg, png, bmp]
    GPU: true
    GPU_ID: 0
    Path: .\projects\NtustNewMailCaptcha\images_set\images\
    Project: NtustNewMailCaptcha
    Val: 0.03
Train:
    BATCH_SIZE: 64
    CNN: {NAME: ddddocr}
    DROPOUT: 0.3
    LR: 0.01
    OPTIMIZER: SGD
    SAVE_CHECKPOINTS_STEP: 300
    TARGET: {Accuracy: 0.98, Cost: 0.05, Epoch: 1}
    TEST_BATCH_SIZE: 64
    TEST_STEP: 300
