Model:
    CharSet: [' ', D, U, '5', '3', P, N, L, Z, R, V, H, B, Y, S, '2', '9', '7', M,
        '8', X, K, G, C, F, W, E, A, J, Q, '6', '4', T]
    ImageChannel: 1
    ImageHeight: 64
    ImageWidth: -1
    Word: false
System:
    Allow_Ext: [jpg, jpeg, png, bmp]
    GPU: true
    GPU_ID: 0
    Path: ./projects/NtustNewMailCaptcha/images_set/images/
    Project: NtustNewMailCaptcha
    Val: 0.03
Train:
    BATCH_SIZE: 64
    CNN: {NAME: ddddocr}
    DROPOUT: 0.3
    LR: 0.01
    OPTIMIZER: SGD
    SAVE_CHECKPOINTS_STEP: 300
    TARGET: {Accuracy: 0.98, Cost: 0.05, Epoch: 1}
    TEST_BATCH_SIZE: 64
    TEST_STEP: 300
